---
# playbook file to set up the machine and install Decidim

- hosts: all
  roles:
    - role: init_container
    - role: docker
    - role: postgresql
    - role: metabase
    - role: nginx
    - role: letsencrypt
